title: Third Place Making
baseURL: https://thirdplacemaking.github.io/
languageCode: en
DefaultContentLanguage: en
Paginate: 10
publishDir: docs
enableRobotsTXT: true
removePathAccents: true
pygmentsUseClasses: true
metaDataFormat: yaml
disableKinds:
- taxonomy
- term