title: Third Place Making
baseURL: /
languageCode: en
DefaultContentLanguage: en
Paginate: 10
publishDir: docs
removePathAccents: true
pygmentsUseClasses: true
metaDataFormat: yaml
disableKinds:
- taxonomy
- term