en:
  weight: 1
  languageName: English
  menu:
    main:
    - identifier: about
      name: About
      url: /about
      weight: 1
    - identifier: contact
      name: Contact
      url: /contact
      weight: 2
    - identifier: newsletter
      name: Newsletter
      url: /newsletter
      weight: 3
    footer1:
    - identifier: case-studies
      name: Case studies
      url: /case-studies
      weight: 1
      pre: (soon)
    - identifier: global-callenges
      name: Global challenges
      url: /global-callenges
      weight: 2
      pre: (soon)
    footer2:
    - identifier: about
      name: Who we are
      url: /about
      weight: 1
    - identifier: contact
      name: Contact
      url: /contact
      weight: 2
    footer3:
    - identifier: publications
      name: Publications 
      url: /publications
      weight: 1
      pre: (soon)
    footer4:
    - identifier: newsletter
      name: Newsletter 
      url: /newsletter
      weight: 1
    - identifier: stories
      name: Stories 
      url: /stories
      weight: 2
      pre: (soon)
    footer:
    # - identifier: privacy-policy
    #   name: Privacy Policy
    #   url: /privacy-policy
    #   weight: 1
    - identifier: legal
      name: Legal notice
      url: /legal-notice
      weight: 2
fr:
  weight: 2
  languageName: Français
  menu:
    main:
    - identifier: about
      name: À propos
      url: /a-propos
      weight: 1
    - identifier: contact
      name: Contact
      url: /contact
      weight: 2
    - identifier: newsletter
      name: Newsletter
      url: /newsletter
      weight: 3
    footer1:
    - identifier: case-studies
      name: Case studies
      url: /case-studies
      weight: 1
      pre: (soon)
    - identifier: global-callenges
      name: Global challenges
      url: /global-callenges
      weight: 2
      pre: (soon)
    footer2:
    - identifier: about
      name: Qui sommes nous
      url: /about
      weight: 1
    - identifier: contact
      name: Contact
      url: /contact
      weight: 2
    footer3:
    - identifier: publications
      name: Publications 
      url: /publications
      weight: 1
      pre: (soon)
    footer4:
    - identifier: newsletter
      name: Newsletter 
      url: /newsletter
      weight: 1
    - identifier: stories
      name: Stories 
      url: /stories
      weight: 2
      pre: (soon)
    footer:
    # - identifier: privacy-policy
    #   name: Politique de confidentialité
    #   url: /politique-confidentialite
    #   weight: 1
    - identifier: legal
      name: Mentions légales
      url: /mentions-legales
      weight: 2
