description: Making the world as a third place
logo: "media/TPM-logo.png"
image: "media/TPM-cover.png"
social:
- title: "Twitter"
  url: "https://twitter.com/3rdPlaceMaking"
- title: "LinkedIn"
  url: "https://www.linkedin.com/company/third-place-making"
- title: "GitHub"
  url: "https://github.com/thirdplacemaking/thirdplacemaking.github.io"
